[build]
jobs = 16                # Set to your CPU core count
rustc-wrapper = "sccache" # Enables disk caching
pipelining = true        # Enables build pipelining

[profile.dev]
incremental = true       # Enable incremental compilation
codegen-units = 16       # Enables parallel code generation